server:
  port: 8081
spring:
  application:
    name: STOCK_SERVICE
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/stock_service_db
    driver-class-name: org.postgresql.Driver
    username: touhid
    password: touhid
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    topic:
      name: order_topic
    consumer:
      bootstrap-servers: 127.0.0.1:29092, 127.0.0.1:39092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: stock
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
management:
  tracing:
    sampling:
      probability: 1.0

logging.file.dir: ${home}/microservice-logs

logging:
  file:
    name: ${logging.file.dir}/stock_service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30